dist: xenial
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: lGHsrswwSgNIdUlPX2SL2kPC3q+uNWSElxNwM9zcgOFJk98zlFbvXkJa/AdLwPJvNJrUW54GaReCslSl9s74tuOKg+tw5R2rx6r9Sx9VBhEgjHt2eR9YC9ELPx9g7zEybTWPXYujgWcxF9OJtQTZPMDT6CC4OlOU1R55Uls1BlmHVjalCXO4AyPMzoCIqHkYlOCzaxo5l1mdpnk48H05bXMzxsBvDkamvPn+rqkDt9DSvVviG+FR5J6dR7LvCV9ehHkyVc+GruF2RwTt4WIjnyf2R52+g2X3aJVYPqzEJLQHHJQ+S7xqGzw2y5UsQ10Ju8KUUwhaTcjWVImUDCHm+07rlm7FrjcnDcaeE8WiGfnHczIf4a0FquevkcAtHJNjz+rSpq2aYc9cGrtHPGerR15EDbXiOK0BCULiuxe9ba24H4d2quez9Q0sfoqJpdHeWNvilHihTMZQZ5nd+JCOpTqHaYI0/LTrutgmBfsqZlxDhxTjThlw5CEEO5ZAf171KxRKd739ulGJ9n0DRBVeg8se6UyYC+nTlw+4hXW1pquNpc3mCqyRMMSwahs4i6O9qPuo24lxzDLt87H2KDfJctwXK3EK7AJD38adDrAZQjrpqQLsdZI04FjTVz1PzwBXJqTw1e9T7GVIOe7mLDkQ5oPtHSC7X1Tqy5dhZ9KK8Uo=
