dist: xenial
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh | bash
notifications:
  slack:
    rooms:
      secure: vSf080ffkBMcsSuR7t0B2t/6CPZImoCQFV1+mWH5P5vqK4/E8tZa6rO8lkwbAdeE0XQpSCzqcn3aIEym8QSYTgjpgXYsN36KhZj12cEy4duRbWy09rICledt5xjoBh1IfMEVVP0ZmRs/fleq5yiB+i6HOefztAqZ53Jy0nqjQCP8OJtVfTAHlpbvpYaQfhPEWecL+GUAb3vEUMq0rWl/PyGD7sRNXJMYF79thqQLTftXKb9lvAMmRkyeC2gntaUwaVev8cOXja3+6PoUV4FWaiSa22qSEYyRv6FngQSpNimBpIsfpMqo2TuKNzTISBEujsZXZH2IcHLZyan10C1TN8fV1s+Ynl7MflQOwXFhxjporc4ZJVp6etc3rOjcg165qqFCsXj/Y3DPpFy/wTJfiV/X2gqIKh3/2a+yyBat3RCvbPrp4wXcerBo4qZOVcTles+kKCufwnALUN8xRyepMXN8aom+BRw9tAprmzodZDAs0763A6uFPFNF0AosyxLXOf86QHW8YqsgnlAMb7/zJ9Bn401cIeZeRgfrY9gKu+u+zPC9oqgJB6GtcwyG3xRa0raUx+3Vel4DWu1xY8XgQ/Xqe/k3n1dasv3bTDFPcAG++fbwszmwLJNzzOSRlQOsr1srkfFLauC22ffDychYk/WD8VGcap7HzQtwOUgIx/Q=
