kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: DISpkgGmcnNu58e9y+/TuyuqTkBqnA98ZGDjbQEMC5A=
      - identity: {}
